name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Create Version Tag
      run: |
        export IMAGE_NAME=m4s-blog:$(date +%Y%m%d.%H%M)
        echo "image_name=$IMAGE_NAME" >> "$GITHUB_ENV"

    - name: Build Docker Image
      run: |
        docker build -t ${{ env.image_name }} .
        docker save -o ${{ env.image_name }} ${{ env.image_name }}

    - name: Push Image to Host via SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: ${{ env.image_name }}
        target: /
  
    - name: Boot Container via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker load -i /${{ env.image_name }}
          docker create --name m4s-blog ${{ env.image_name }}
          docker start m4s-blog