name: Deploy to m4s server

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: ssh commands to build and run docker image on the server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.M4S_HOST }}
        username: ${{ secrets.M4S_USERNAME }}
        password: ${{ secrets.M4S_PASSWORD }}
        port: ${{ secrets.M4S_PORT }}
        key:  ${{ secrets.M4S_KEY }}
        script: whoami