name: deploy

on:
  push:
    branches:
      - main

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image
      uses: actions/checkout@v3
      env:
        IMAGE_NAME: m4s-blog:$(date +%Y%m%d.%H%M)
    - run: |
        echo "image_name=$IMAGE_NAME" >> "$GITHUB_ENV"
        docker build -t $IMAGE_NAME .
        docker save -o /$IMAGE_NAME $IMAGE_NAME
  
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Copy image via ssh/scp to host
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: /${{ env.image_name }}
        target: /
  
  boot:
    runs-on: ubuntu-latest
    steps:
    - name: SSH into host and start container
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker load -i /${{ env.image_name }}
          docker create --name m4s-blog ${{ env.image_name }}
          docker start m4s-blog